name: ar1
ar:
  coeffs:
    mu: 0
    sigma: 1
  init:
    mu: 1.2
    sigma: 1
  sigma: 1
  size: 2
# seasonality:
#   init:
#     mu: 0
#     sigma: 1
#   sigma: 2
#   size: 11
# trend:
#   init:
#     mu: 0
#     sigma: 1
#   sigma: 2
#   slope:
#     init:
#       mu: 0
#       sigma: 2
#     sigma: 1
sigma: 2
